import React, { useState, useEffect } from "react";
import { View, Text, TouchableOpacity, StyleSheet, Platform } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { WebView } from "react-native-webview";
import { getTemplateWithCacheBust, forceRefreshTemplate } from "../../utils/pdfWatcher";
import { generatePdfFromHtml } from "../../utils/pdfUtils";
import * as Sharing from "expo-sharing";

// ⚠️ DO NOT EDIT THIS FILE FOR TEMPLATE CHANGES!
// Edit: /components/pdf/winterFellPdf.js → TemplateJourneyRouters function

export default function DevPdfPreview() {
  const [htmlContent, setHtmlContent] = useState("");
  const [refreshKey, setRefreshKey] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);

  // Sample data for testing
  const sampleData = {
    TripId: "JR-TRIP-2401",
    DestinationName: "Bali",
    FullName: "Rahul Sharma",
    TravelDate: "2025-03-10",
    Days: 6,
    TotalCost: 98500,
    CurrencyType: "INR",
    PriceType: "Per Person",
    PhoneNumber: "8368045646",
    GoogleReviewCount: "1,500+",
    NoOfPax: 2,
    Child: 1,
    Infant: 0,
    Inclusions: ["Return airfare", "5N stay with breakfast", "Private transfers", "City tour with guide"],
    OtherInclusions: "Travel insurance\\nVisa assistance",
    Exclusions: ["Lunch & Dinner", "Personal expenses", "Early check-in / late check-out"],
    OtherExclusions: "Tips and gratuities\\nOptional activities",
    Itinearies: [
      { 
        title: "Arrival & Beach Relaxation", 
        description: "Airport pickup and hotel transfer\\nEvening beach walk\\nWelcome dinner",
        activityImg: "https://firebasestorage.googleapis.com/v0/b/destination_image/o/BALI%2FArival.png?alt=media",
        activities: "Arrival"
      },
      { 
        title: "Water Sports Adventure", 
        description: "Banana boat ride\\nJet ski experience\\nParasailing adventure\\nBeach lunch",
        activityImg: "https://firebasestorage.googleapis.com/v0/b/destination_image/o/BALI%2FWaterSports.png?alt=media",
        activities: "Water Sports"
      },
      { 
        title: "Cultural Tour", 
        description: "Visit Uluwatu Temple\\nKecak dance performance\\nSeafood dinner at Jimbaran",
        activityImg: "https://firebasestorage.googleapis.com/v0/b/destination_image/o/BALI%2FCulturalTour.png?alt=media",
        activities: "Cultural"
      },
    ],
    Hotels: [
      { 
        name: "Grand Kuta Hotel", 
        city: "Kuta", 
        category: 4,
        roomType: "Deluxe Ocean View",
        nights: ["Night 1", "Night 2", "Night 3"],
        meals: ["Breakfast", "Dinner"],
        checkInDate: "10th Mar 2025",
        checkOutDate: "13th Mar 2025"
      }
    ],
    flightsImagesLinks: ["https://via.placeholder.com/1000x400?text=Flight+Details"],
  };

  // Generate HTML on mount and when refresh is triggered
  const generateHtml = () => {
    console.log("🔄 Generating HTML from template...");
    const Template = getTemplateWithCacheBust();
    const html = Template(sampleData);
    setHtmlContent(html);
    console.log("✅ HTML generated, length:", html.length);
  };

  useEffect(() => {
    generateHtml();
  }, [refreshKey]);

  // Auto-refresh every 3 seconds to catch template changes
  useEffect(() => {
    const interval = setInterval(() => {
      console.log("⏰ Auto-refreshing template...");
      forceRefreshTemplate();
      generateHtml();
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const handleManualRefresh = () => {
    console.log("🔄 Manual refresh triggered");
    forceRefreshTemplate();
    setRefreshKey((prev) => prev + 1);
  };

  const handleDownloadPdf = async () => {
    try {
      setIsGenerating(true);
      console.log("📄 Generating PDF...");
      const pdfUri = await generatePdfFromHtml(htmlContent);
      console.log("✅ PDF generated:", pdfUri);
      
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(pdfUri, {
          UTI: '.pdf',
          mimeType: 'application/pdf',
        });
      }
    } catch (error) {
      console.error("❌ Error generating PDF:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>🔥 Real-time PDF Preview</Text>
        <Text style={styles.subtitle}>Edit winterFellPdf.js to see changes</Text>
      </View>

      {/* Controls */}
      <View style={styles.controls}>
        <TouchableOpacity 
          style={styles.refreshBtn} 
          onPress={handleManualRefresh}
        >
          <Ionicons name="refresh" size={20} color="#fff" />
          <Text style={styles.btnText}>Refresh Now</Text>
        </TouchableOpacity>

        <TouchableOpacity 
          style={[styles.downloadBtn, isGenerating && styles.btnDisabled]} 
          onPress={handleDownloadPdf}
          disabled={isGenerating}
        >
          <Ionicons name="download" size={20} color="#fff" />
          <Text style={styles.btnText}>
            {isGenerating ? "Generating..." : "Download PDF"}
          </Text>
        </TouchableOpacity>
      </View>

      {/* Preview */}
      <View style={styles.previewContainer}>
        {htmlContent ? (
          <WebView
            key={refreshKey}
            source={{ html: htmlContent }}
            style={styles.webview}
            startInLoadingState={true}
            scalesPageToFit={Platform.OS === 'android'}
          />
        ) : (
          <View style={styles.loading}>
            <Text style={styles.loadingText}>Loading preview...</Text>
          </View>
        )}
      </View>

      {/* Info */}
      <View style={styles.info}>
        <Text style={styles.infoText}>
          ⚡ Auto-refreshes every 3 seconds (or click Refresh Now)
        </Text>
        <Text style={styles.infoText}>
          📝 Edit: components/pdf/winterFellPdf.js → TemplateJourneyRouters
        </Text>
        <Text style={styles.infoText}>
          💡 Save file (Cmd+S) and wait for refresh
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#0a0a0a",
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  title: { 
    color: "#fff", 
    fontSize: 24, 
    fontWeight: "700",
    marginBottom: 4,
  },
  subtitle: {
    color: "#888",
    fontSize: 14,
  },
  controls: {
    flexDirection: "row",
    padding: 12,
    gap: 12,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  refreshBtn: {
    flex: 1,
    backgroundColor: "#10b981",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderRadius: 8,
    gap: 8,
  },
  downloadBtn: {
    flex: 1,
    backgroundColor: "#7c3aed",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderRadius: 8,
    gap: 8,
  },
  btnDisabled: {
    opacity: 0.6,
  },
  btnText: { 
    color: "#fff", 
    fontSize: 14, 
    fontWeight: "600" 
  },
  previewContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  webview: {
    flex: 1,
    backgroundColor: "#000",
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#888",
    fontSize: 16,
  },
  info: {
    padding: 12,
    backgroundColor: "#1a1a1a",
    borderTopWidth: 1,
    borderTopColor: "#333",
  },
  infoText: {
    color: "#888",
    fontSize: 12,
    textAlign: "center",
    marginVertical: 2,
  },
});
